### ISSUE TITLE
Fastrtpsgen changed name into fastddsgen

### ISSUE THREAD

**Issue by Andrea2202** [PX4/px4_ros_com#67]
Since the latest version of the repo https://github.com/eProsima/Fast-DDS-Gen.git the name has been changed to fastddsgen.
Is it possible to adapt the scripts to the latest version?

**Comment by TSC21** [comment]
We only support fastrtpsgen until version 1.0.4. fastddsgen (2.0.0) only generates DDS API, and they deprecated the RTPS API (you can read it in the release notes https://github.com/eProsima/Fast-DDS-Gen/releases/tag/v2.0.0). So this will only be possible as soon as we update outlr templates as well to use the DDS API instead of the RTPS API.
This is on the plans but not high priority.
